Fogl 526
foglamp/foglamp-snap pull request #8
Opened 2018-02-02 15:48 UTC by pintomax

The 'scripts/task/update is a "package" dependent script which calls the right package manager script/utility in the system

For Snap we provide a 'snap-get.sh' script which manages snaps from a configurable repository.

The repository default URL is set in 'scripts/task/update' script and it can be overwritten by an API call to the category name, the key is 'repository'

**Example with category name 'SNAP_UPD'**

```json
{
  "repository": {
    "value": "https://s3.amazonaws.com/foglamp",
    "default": "https://s3.amazonaws.com/foglamp",
    "type": "string",
    "description": "Remote repository for package manager"
  },
  "package": {
    "value": "SNAP",
    "default": "Snap",
    "type": "string",
    "description": "Package manager type"
  }
}
```

**Example from package building phase**

$ sudo snapcraft

```
Copying Update Task 'scripts/update' to /home/ubuntu/source/foglamp-snap/parts/foglamp/install/usr/local/foglamp/scripts/tasks ... done
Copying Snap Updater 'scripts/snap-get.sh' to /home/ubuntu/source/foglamp-snap/parts/foglamp/install/usr/local/foglamp/scripts/common ... done
```

2018-02-06 09:32 UTC, izoratti approved these changes

2018-02-09 17:23 UTC, MarkRiddoch requested changes

2018-02-09 17:23 UTC, MarkRiddoch commented on snapcraft.yaml
> +        - wget
Do we really need curl and wget?

2018-02-09 17:23 UTC, MarkRiddoch commented on scripts/package/snap-get.sh
> +	sudo snap install ${DEVMODE} ./${NAME}
We need to think very carefully about how sudo is going to work here. There is no requirement to have the foglamp user able to sudo at the moment.

We may need to consider an option such as setuid on execution script to get around this for example.

2018-02-09 17:38 UTC, pintomax commented on snapcraft.yaml
> +        - wget
wget has been removed.

Curl is used to download snaps from remote repository

2018-02-16 15:14 UTC, izoratti approved these changes

2018-02-19 10:52 UTC, merged